on:
  push:
    branches:
    - main
env:
  DOTNET_CORE_VERSION: 8.0.x
  CONTAINER_APP_NAME: sioms.webapi-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnvironment-practiceazure-b2d1
  RESOURCE_GROUP: practice-azure
  CONTAINER_REGISTRY_NAME: siomscontainerregistry
  CONTAINER_REGISTRY_LOGIN_SERVER: siomscontainerregistry.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnvironment_practiceazure_b2d1_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.siomscontainerregistry_USERNAME_59F0 }}
        acrPassword: ${{ secrets.siomscontainerregistry_PASSWORD_59F0 }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
